[web]
34.93.129.245 ansible_user=jenish ansible_ssh_private_key_file=~/.ssh/google_compute_engine
34.68.123.39 ansible_user=jenish ansible_ssh_private_key_file=~/.ssh/google_compute_engine

#cd ~/spe/MiniProject/scientific-calculator/ansible-deploy
#ansible -i inventory.ini web -m ping